[package]
name = "async-graphql-actix-web"
version = "2.8.4"
authors = ["sunli <scott_s829@163.com>", "Koxiaet"]
edition = "2018"
description = "async-graphql for actix-web"
license = "MIT/Apache-2.0"
documentation = "https://docs.rs/async-graphql-actix-web/"
homepage = "https://github.com/async-graphql/async-graphql"
repository = "https://github.com/async-graphql/async-graphql"
keywords = ["futures", "async", "graphql"]
categories = ["network-programming", "asynchronous"]

[dependencies]
async-graphql = { path = "../..", version = "=2.8.4" }

actix = "0.10.0"
actix-http = "2.2.0"
actix-web = { version = "3.3.2", default-features = false }
actix-web-actors = "3.0.0"
async-channel = "1.6.1"
futures-util = { version = "0.3.13", default-features = false }
serde_json = "1.0.64"
serde_urlencoded = "0.7.0"

[dev-dependencies]
actix-rt = "1.1.0"
async-mutex = "1.4.0"
